#!/usr/bin/env python3
# lang.py – OLED UI string translations
# Only Latin-script languages are included (compatible with default PIL font).
# Max ~25 characters per string to fit the 128px OLED width.

from __future__ import annotations
from typing import Optional

# ── Active language (set once at startup) ────────────────────────────
_current: str = "en"

def set_language(code: str) -> None:
    global _current
    code = (code or "en").strip().lower()
    if code not in STRINGS:
        print(f"[LANG] Unknown language '{code}', falling back to 'en'")
        code = "en"
    _current = code
    print(f"[LANG] Language set to: {_current}")

def get_language() -> str:
    return _current

def t(key: str) -> str:
    """Look up a translated string by key.  Falls back to English."""
    return STRINGS.get(_current, {}).get(key) or STRINGS["en"].get(key, key)

# ── Supported languages ──────────────────────────────────────────────
# (code, native_name, english_name)
LANGUAGES = [
    ("en", "English",    "English"),
    ("es", "Español",    "Spanish"),
    ("fr", "Français",   "French"),
    ("de", "Deutsch",    "German"),
    ("it", "Italiano",   "Italian"),
    ("pt", "Português",  "Portuguese"),
    ("nl", "Nederlands", "Dutch"),
    ("sv", "Svenska",    "Swedish"),
    ("da", "Dansk",      "Danish"),
    ("no", "Norsk",      "Norwegian"),
]

# ── String tables ────────────────────────────────────────────────────
# Keys are used by oled_ui.py and main.py.
# Every value must be ≤ 25 characters to fit the OLED.

STRINGS = {

# ─────────────────────────── English ──────────────────────────────────
"en": {
    # Screen 0 – Info
    "otp":              "OTP",
    "time":             "Time",
    "hue":              "Hue",
    "bright":           "Bright",
    "press_next":       "[Press: Next Screen]",

    # Screen 1 – Color
    "color_title":      "COLOR",
    "rotate_color":     "Rotate: change Color",
    "press_next_short": "[Press: Next]",

    # Screen 2 – Brightness
    "bright_title":     "BRIGHTNESS",
    "level":            "Level",
    "lang_title":      "LANGUAGE",
    "rotate_lang":     "Rotate: change lang",

    # Screen 3 – Reset menu
    "reset_title":      "RESET MENU",
    "next_screen":      "Next Screen",
    "reset_wifi":       "Reset Wi-Fi",
    "reset_qr":         "Reset QR",
    "reset_both":       "Reset Both",
    "scroll_hint":      "Rotate to select, Press to choose",

    # Screen 4 – Confirm
    "confirm_title":    "CONFIRM",
    "confirm_wifi":     "Reset Wi-Fi?",
    "confirm_qr":       "Reset QR?",
    "confirm_both":     "Reset BOTH?",
    "press_yes":        "Press = YES",
    "rotate_cancel":    "Rotate = NO/Cancel",
    "restarts_after":   "App restarts after",

    # Reset flow
    "resetting":        "RESETTING...",
    "action":           "Action",
    "system_reboot":    "System will reboot",
    "please_wait":      "Please wait...",
    "files_deleted":    "FILES DELETED",
    "rebooting":        "Rebooting system...",
    "wait_reboot":      "Wait for reboot",

    # Setup (main.py progressive screens)
    "setup_title":      "OTPi SETUP",
    "setup_starting":   "Starting setup...",
    "setup_step1":      "SETUP STEP 1",
    "setup_connect":    "Connect device to:",
    "setup_step2":      "SETUP STEP 2",
    "setup_browser":    "Open web browser",
    "setup_navigate":   "Navigate to:",
    "setup_step3":      "SETUP STEP 3",
    "setup_form":       "Complete the form",
    "setup_on_web":     "on the webpage",
    "setup_complete":   "SETUP COMPLETE",
    "setup_saved":      "Configuration saved",
    "setup_restarting": "Restarting device...",
    "setup_error":      "SETUP ERROR",
    "setup_check":      "Check webpage",

    # Splash
    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Time sync OK",
    "starting":         "Starting display...",

    # Web portal strings
    "web_title": "OTPi Setup",
    "web_footer": "Device address",
    "web_nothing": "Nothing to configure.",
    "web_msg_both": "Please provide Wi-Fi credentials and a QR code to continue.",
    "web_msg_wifi": "Please provide Wi-Fi credentials to continue.",
    "web_msg_qr": "Please upload your QR code to continue.",
    "web_wifi_title": "Wi-Fi Configuration",
    "web_country_label": "Country / Region",
    "web_country_hint": "Sets the WiFi regulatory domain for your country.",
    "web_lang_label": "Display Language",
    "web_lang_hint": "Language for the device display and this page.",
    "web_ssid_label": "Network (SSID)",
    "web_ssid_manual_label": "Enter SSID manually",
    "web_ssid_placeholder": "Your network name",
    "web_password_label": "Password",
    "web_qr_title": "OTP QR Code",
    "web_qr_label": "Upload QR Code Image",
    "web_qr_hint": "Accepts PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Complete Setup",
    "web_btn_wifi": "Save Wi-Fi",
    "web_btn_qr": "Upload QR",
    "web_status_fill": "Please fill in all fields above",
    "web_status_select": "Select a network and enter a password",
    "web_status_ready": "Ready to save configuration",
    "web_status_ready_short": "Ready to save",
    "web_status_saving": "Saving...",
    "web_status_processing": "Processing configuration...",
    "web_missing_prefix": "Missing",
    "web_scanning": "Scanning...",
    "web_no_networks": "No networks found",
    "web_select_network": "Select your network",
    "web_not_shown": "My WiFi is not shown...",
    "web_field_ssid": "SSID",
    "web_field_password": "Password",
    "web_field_qr": "QR Code",
    "web_success_title": "Setup Complete!",
    "web_success_saved": "Successfully saved",
    "web_success_disconnect": "You can now disconnect from the setup network.",
    "web_success_restart": "The device will restart and begin normal operation.",
    "web_success_totp": "Your TOTP codes will be displayed on the LED matrix.",
    "web_error_incomplete": "Setup incomplete.",
    "web_error_back": "Back",
    "web_error_missing_wifi": "Wi-Fi credentials",
    "web_error_missing_qr": "QR code",
    "web_error_empty": "Uploaded file is empty",
    "web_error_not_image": "is not a valid image file",
},

# ─────────────────────────── Spanish ─────────────────────────────────
"es": {
    "otp":              "OTP",
    "time":             "Tiempo",
    "hue":              "Tono",
    "bright":           "Brillo",
    "press_next":       "[Pulsar: Siguiente]",

    "color_title":      "COLOR",
    "rotate_color":     "Girar: cambiar Color",
    "press_next_short": "[Pulsar: Sig.]",

    "bright_title":     "BRILLO",
    "level":            "Nivel",
    "lang_title":      "IDIOMA",
    "rotate_lang":     "Girar: mudar idioma",
    "lang_title":      "IDIOMA",
    "rotate_lang":     "Girar: cambiar idioma",

    "reset_title":      "MENU REINICIO",
    "next_screen":      "Siguiente",
    "reset_wifi":       "Reiniciar Wi-Fi",
    "reset_qr":         "Reiniciar QR",
    "reset_both":       "Reiniciar ambos",
    "scroll_hint":      "Girar para elegir, Pulsar para confirmar",

    "confirm_title":    "CONFIRMAR",
    "confirm_wifi":     "Reiniciar Wi-Fi?",
    "confirm_qr":       "Reiniciar QR?",
    "confirm_both":     "Reiniciar TODO?",
    "press_yes":        "Pulsar = SI",
    "rotate_cancel":    "Girar = Cancelar",
    "restarts_after":   "Se reinicia despues",

    "resetting":        "REINICIANDO...",
    "action":           "Accion",
    "system_reboot":    "Reinicio del sistema",
    "please_wait":      "Espere por favor...",
    "files_deleted":    "ARCHIVOS BORRADOS",
    "rebooting":        "Reiniciando...",
    "wait_reboot":      "Espere el reinicio",

    "setup_title":      "OTPi CONFIG",
    "setup_starting":   "Iniciando config...",
    "setup_step1":      "PASO 1",
    "setup_connect":    "Conectar al Wi-Fi:",
    "setup_step2":      "PASO 2",
    "setup_browser":    "Abrir navegador web",
    "setup_navigate":   "Ir a:",
    "setup_step3":      "PASO 3",
    "setup_form":       "Completar formulario",
    "setup_on_web":     "en la pagina web",
    "setup_complete":   "CONFIG COMPLETA",
    "setup_saved":      "Config guardada",
    "setup_restarting": "Reiniciando...",
    "setup_error":      "ERROR DE CONFIG",
    "setup_check":      "Revisar pagina web",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Hora sincronizada",
    "starting":         "Iniciando...",

    # Web portal strings
    "web_title": "OTPi Configuração",
    "web_footer": "Endereço do dispositivo",
    "web_nothing": "Nada para configurar.",
    "web_msg_both": "Forneça as credenciais Wi-Fi e um código QR para continuar.",
    "web_msg_wifi": "Forneça as credenciais Wi-Fi para continuar.",
    "web_msg_qr": "Envie seu código QR para continuar.",
    "web_wifi_title": "Configuração Wi-Fi",
    "web_country_label": "País / Região",
    "web_country_hint": "Define o domínio regulatório Wi-Fi do seu país.",
    "web_lang_label": "Idioma da tela",
    "web_lang_hint": "Idioma para a tela e esta página.",
    "web_ssid_label": "Rede (SSID)",
    "web_ssid_manual_label": "Inserir SSID manualmente",
    "web_ssid_placeholder": "Nome da sua rede",
    "web_password_label": "Senha",
    "web_qr_title": "Código QR OTP",
    "web_qr_label": "Enviar imagem do código QR",
    "web_qr_hint": "Aceita PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Concluir configuração",
    "web_btn_wifi": "Salvar Wi-Fi",
    "web_btn_qr": "Enviar QR",
    "web_status_fill": "Preencha todos os campos",
    "web_status_select": "Selecione uma rede e insira a senha",
    "web_status_ready": "Pronto para salvar",
    "web_status_ready_short": "Pronto para salvar",
    "web_status_saving": "Salvando...",
    "web_status_processing": "Processando configuração...",
    "web_missing_prefix": "Faltando",
    "web_scanning": "Buscando...",
    "web_no_networks": "Nenhuma rede encontrada",
    "web_select_network": "Selecione sua rede",
    "web_not_shown": "Meu WiFi não aparece...",
    "web_field_ssid": "SSID",
    "web_field_password": "Senha",
    "web_field_qr": "Código QR",
    "web_success_title": "Configuração concluída!",
    "web_success_saved": "Salvo com sucesso",
    "web_success_disconnect": "Você pode desconectar da rede de configuração.",
    "web_success_restart": "O dispositivo vai reiniciar e começar a funcionar.",
    "web_success_totp": "Os códigos TOTP serão exibidos no display LED.",
    "web_error_incomplete": "Configuração incompleta.",
    "web_error_back": "Voltar",
    "web_error_missing_wifi": "Credenciais Wi-Fi",
    "web_error_missing_qr": "Código QR",
    "web_error_empty": "O arquivo enviado está vazio",
    "web_error_not_image": "não é um arquivo de imagem válido",

    # Web portal strings
    "web_title": "OTPi Configuración",
    "web_footer": "Dirección del dispositivo",
    "web_nothing": "Nada que configurar.",
    "web_msg_both": "Proporcione las credenciales Wi-Fi y un código QR para continuar.",
    "web_msg_wifi": "Proporcione las credenciales Wi-Fi para continuar.",
    "web_msg_qr": "Suba su código QR para continuar.",
    "web_wifi_title": "Configuración Wi-Fi",
    "web_country_label": "País / Región",
    "web_country_hint": "Establece el dominio regulatorio Wi-Fi de su país.",
    "web_lang_label": "Idioma de pantalla",
    "web_lang_hint": "Idioma para la pantalla del dispositivo y esta página.",
    "web_ssid_label": "Red (SSID)",
    "web_ssid_manual_label": "Ingrese SSID manualmente",
    "web_ssid_placeholder": "Nombre de su red",
    "web_password_label": "Contraseña",
    "web_qr_title": "Código QR OTP",
    "web_qr_label": "Subir imagen de código QR",
    "web_qr_hint": "Acepta PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Completar configuración",
    "web_btn_wifi": "Guardar Wi-Fi",
    "web_btn_qr": "Subir QR",
    "web_status_fill": "Complete todos los campos",
    "web_status_select": "Seleccione una red e ingrese contraseña",
    "web_status_ready": "Listo para guardar",
    "web_status_ready_short": "Listo para guardar",
    "web_status_saving": "Guardando...",
    "web_status_processing": "Procesando configuración...",
    "web_missing_prefix": "Falta",
    "web_scanning": "Buscando...",
    "web_no_networks": "No se encontraron redes",
    "web_select_network": "Seleccione su red",
    "web_not_shown": "Mi WiFi no aparece...",
    "web_field_ssid": "SSID",
    "web_field_password": "Contraseña",
    "web_field_qr": "Código QR",
    "web_success_title": "¡Configuración completa!",
    "web_success_saved": "Guardado exitosamente",
    "web_success_disconnect": "Puede desconectarse de la red de configuración.",
    "web_success_restart": "El dispositivo se reiniciará y comenzará a funcionar.",
    "web_success_totp": "Los códigos TOTP se mostrarán en la pantalla LED.",
    "web_error_incomplete": "Configuración incompleta.",
    "web_error_back": "Volver",
    "web_error_missing_wifi": "Credenciales Wi-Fi",
    "web_error_missing_qr": "Código QR",
    "web_error_empty": "El archivo subido está vacío",
    "web_error_not_image": "no es un archivo de imagen válido",
},

# ─────────────────────────── French ──────────────────────────────────
"fr": {
    "otp":              "OTP",
    "time":             "Temps",
    "hue":              "Teinte",
    "bright":           "Lum.",
    "press_next":       "[Appuyer: Suivant]",

    "color_title":      "COULEUR",
    "rotate_color":     "Tourner: Couleur",
    "press_next_short": "[Appuyer: Suiv.]",

    "bright_title":     "LUMINOSITE",
    "level":            "Niveau",
    "lang_title":      "SPROG",
    "rotate_lang":     "Drej: skift Sprog",
    "lang_title":      "TAAL",
    "rotate_lang":     "Draai: taal wijzigen",
    "lang_title":      "LANGUE",
    "rotate_lang":     "Tourner: changer lang",

    "reset_title":      "REINITIALISATION",
    "next_screen":      "Suivant",
    "reset_wifi":       "Reinit. Wi-Fi",
    "reset_qr":         "Reinit. QR",
    "reset_both":       "Tout reinitialiser",
    "scroll_hint":      "Tourner pour choisir, Appuyer pour valider",

    "confirm_title":    "CONFIRMER",
    "confirm_wifi":     "Reinit. Wi-Fi?",
    "confirm_qr":       "Reinit. QR?",
    "confirm_both":     "Tout reinit.?",
    "press_yes":        "Appuyer = OUI",
    "rotate_cancel":    "Tourner = Annuler",
    "restarts_after":   "Redemarrage apres",

    "resetting":        "REINITIALISATION...",
    "action":           "Action",
    "system_reboot":    "Redemarrage systeme",
    "please_wait":      "Patientez...",
    "files_deleted":    "FICHIERS SUPPRIMES",
    "rebooting":        "Redemarrage...",
    "wait_reboot":      "Veuillez patienter",

    "setup_title":      "OTPi CONFIG",
    "setup_starting":   "Demarrage config...",
    "setup_step1":      "ETAPE 1",
    "setup_connect":    "Connecter au Wi-Fi:",
    "setup_step2":      "ETAPE 2",
    "setup_browser":    "Ouvrir navigateur",
    "setup_navigate":   "Aller a:",
    "setup_step3":      "ETAPE 3",
    "setup_form":       "Remplir formulaire",
    "setup_on_web":     "sur la page web",
    "setup_complete":   "CONFIG TERMINEE",
    "setup_saved":      "Config enregistree",
    "setup_restarting": "Redemarrage...",
    "setup_error":      "ERREUR CONFIG",
    "setup_check":      "Verifier page web",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Heure sync OK",
    "starting":         "Demarrage...",

    # Web portal strings
    "web_title": "OTPi Configuration",
    "web_footer": "Adresse de l'appareil",
    "web_nothing": "Rien à configurer.",
    "web_msg_both": "Veuillez fournir les identifiants Wi-Fi et un code QR pour continuer.",
    "web_msg_wifi": "Veuillez fournir les identifiants Wi-Fi pour continuer.",
    "web_msg_qr": "Veuillez télécharger votre code QR pour continuer.",
    "web_wifi_title": "Configuration Wi-Fi",
    "web_country_label": "Pays / Région",
    "web_country_hint": "Définit le domaine réglementaire Wi-Fi de votre pays.",
    "web_lang_label": "Langue d'affichage",
    "web_lang_hint": "Langue de l'écran et de cette page.",
    "web_ssid_label": "Réseau (SSID)",
    "web_ssid_manual_label": "Saisir le SSID manuellement",
    "web_ssid_placeholder": "Nom de votre réseau",
    "web_password_label": "Mot de passe",
    "web_qr_title": "Code QR OTP",
    "web_qr_label": "Télécharger l'image du code QR",
    "web_qr_hint": "Accepte PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Terminer la configuration",
    "web_btn_wifi": "Enregistrer Wi-Fi",
    "web_btn_qr": "Télécharger QR",
    "web_status_fill": "Veuillez remplir tous les champs",
    "web_status_select": "Sélectionnez un réseau et entrez un mot de passe",
    "web_status_ready": "Prêt à enregistrer",
    "web_status_ready_short": "Prêt à enregistrer",
    "web_status_saving": "Enregistrement...",
    "web_status_processing": "Traitement de la configuration...",
    "web_missing_prefix": "Manquant",
    "web_scanning": "Recherche...",
    "web_no_networks": "Aucun réseau trouvé",
    "web_select_network": "Sélectionnez votre réseau",
    "web_not_shown": "Mon WiFi n'apparaît pas...",
    "web_field_ssid": "SSID",
    "web_field_password": "Mot de passe",
    "web_field_qr": "Code QR",
    "web_success_title": "Configuration terminée !",
    "web_success_saved": "Enregistré avec succès",
    "web_success_disconnect": "Vous pouvez vous déconnecter du réseau de configuration.",
    "web_success_restart": "L'appareil va redémarrer et commencer à fonctionner.",
    "web_success_totp": "Les codes TOTP seront affichés sur l'écran LED.",
    "web_error_incomplete": "Configuration incomplète.",
    "web_error_back": "Retour",
    "web_error_missing_wifi": "Identifiants Wi-Fi",
    "web_error_missing_qr": "Code QR",
    "web_error_empty": "Le fichier est vide",
    "web_error_not_image": "n'est pas un fichier image valide",
},

# ─────────────────────────── German ──────────────────────────────────
"de": {
    "otp":              "OTP",
    "time":             "Zeit",
    "hue":              "Farbton",
    "bright":           "Helligk.",
    "press_next":       "[Druecken: Weiter]",

    "color_title":      "FARBE",
    "rotate_color":     "Drehen: Farbe aendern",
    "press_next_short": "[Druecken: Weiter]",

    "bright_title":     "HELLIGKEIT",
    "level":            "Stufe",
    "lang_title":      "SPRACHE",
    "rotate_lang":     "Drehen: Sprache wahl",

    "reset_title":      "RESET MENU",
    "next_screen":      "Weiter",
    "reset_wifi":       "Wi-Fi zuruecksetzen",
    "reset_qr":         "QR zuruecksetzen",
    "reset_both":       "Alles zuruecksetzen",
    "scroll_hint":      "Drehen zum Waehlen, Druecken zum Bestaetigen",

    "confirm_title":    "BESTAETIGEN",
    "confirm_wifi":     "Wi-Fi zuruecksetzen?",
    "confirm_qr":       "QR zuruecksetzen?",
    "confirm_both":     "ALLES zuruecksetzen?",
    "press_yes":        "Druecken = JA",
    "rotate_cancel":    "Drehen = Abbrechen",
    "restarts_after":   "Neustart danach",

    "resetting":        "ZURUECKSETZEN...",
    "action":           "Aktion",
    "system_reboot":    "System Neustart",
    "please_wait":      "Bitte warten...",
    "files_deleted":    "DATEIEN GELOESCHT",
    "rebooting":        "Neustart...",
    "wait_reboot":      "Bitte warten",

    "setup_title":      "OTPi EINRICHTUNG",
    "setup_starting":   "Starte Einrichtung...",
    "setup_step1":      "SCHRITT 1",
    "setup_connect":    "Verbinden mit:",
    "setup_step2":      "SCHRITT 2",
    "setup_browser":    "Browser oeffnen",
    "setup_navigate":   "Gehe zu:",
    "setup_step3":      "SCHRITT 3",
    "setup_form":       "Formular ausfuellen",
    "setup_on_web":     "auf der Webseite",
    "setup_complete":   "EINRICHTUNG FERTIG",
    "setup_saved":      "Einstellung gespeich.",
    "setup_restarting": "Neustart...",
    "setup_error":      "EINRICHTUNGSFEHLER",
    "setup_check":      "Webseite pruefen",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Zeitsync OK",
    "starting":         "Starte Anzeige...",

    # Web portal strings
    "web_title": "OTPi Einrichtung",
    "web_footer": "Geräteadresse",
    "web_nothing": "Nichts zu konfigurieren.",
    "web_msg_both": "Bitte geben Sie WLAN-Zugangsdaten und einen QR-Code ein.",
    "web_msg_wifi": "Bitte geben Sie WLAN-Zugangsdaten ein.",
    "web_msg_qr": "Bitte laden Sie Ihren QR-Code hoch.",
    "web_wifi_title": "WLAN-Konfiguration",
    "web_country_label": "Land / Region",
    "web_country_hint": "Legt die WLAN-Regulierungsdomäne für Ihr Land fest.",
    "web_lang_label": "Anzeigesprache",
    "web_lang_hint": "Sprache für das Display und diese Seite.",
    "web_ssid_label": "Netzwerk (SSID)",
    "web_ssid_manual_label": "SSID manuell eingeben",
    "web_ssid_placeholder": "Ihr Netzwerkname",
    "web_password_label": "Passwort",
    "web_qr_title": "OTP QR-Code",
    "web_qr_label": "QR-Code Bild hochladen",
    "web_qr_hint": "Akzeptiert PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Einrichtung abschließen",
    "web_btn_wifi": "WLAN speichern",
    "web_btn_qr": "QR hochladen",
    "web_status_fill": "Bitte alle Felder ausfüllen",
    "web_status_select": "Netzwerk wählen und Passwort eingeben",
    "web_status_ready": "Bereit zum Speichern",
    "web_status_ready_short": "Bereit zum Speichern",
    "web_status_saving": "Speichern...",
    "web_status_processing": "Konfiguration wird verarbeitet...",
    "web_missing_prefix": "Fehlt",
    "web_scanning": "Suche...",
    "web_no_networks": "Keine Netzwerke gefunden",
    "web_select_network": "Wählen Sie Ihr Netzwerk",
    "web_not_shown": "Mein WLAN wird nicht angezeigt...",
    "web_field_ssid": "SSID",
    "web_field_password": "Passwort",
    "web_field_qr": "QR-Code",
    "web_success_title": "Einrichtung abgeschlossen!",
    "web_success_saved": "Erfolgreich gespeichert",
    "web_success_disconnect": "Sie können sich jetzt vom Einrichtungsnetzwerk trennen.",
    "web_success_restart": "Das Gerät startet neu und beginnt den Normalbetrieb.",
    "web_success_totp": "Die TOTP-Codes werden auf dem LED-Display angezeigt.",
    "web_error_incomplete": "Einrichtung unvollständig.",
    "web_error_back": "Zurück",
    "web_error_missing_wifi": "WLAN-Zugangsdaten",
    "web_error_missing_qr": "QR-Code",
    "web_error_empty": "Hochgeladene Datei ist leer",
    "web_error_not_image": "ist keine gültige Bilddatei",
},

# ─────────────────────────── Italian ─────────────────────────────────
"it": {
    "otp":              "OTP",
    "time":             "Tempo",
    "hue":              "Tinta",
    "bright":           "Lumin.",
    "press_next":       "[Premi: Avanti]",

    "color_title":      "COLORE",
    "rotate_color":     "Ruota: cambia Colore",
    "press_next_short": "[Premi: Avanti]",

    "bright_title":     "LUMINOSITA",
    "level":            "Livello",
    "lang_title":      "LINGUA",
    "rotate_lang":     "Ruota: cambia lingua",

    "reset_title":      "MENU RESET",
    "next_screen":      "Avanti",
    "reset_wifi":       "Reset Wi-Fi",
    "reset_qr":         "Reset QR",
    "reset_both":       "Reset tutto",
    "scroll_hint":      "Ruota per scegliere, Premi per confermare",

    "confirm_title":    "CONFERMA",
    "confirm_wifi":     "Reset Wi-Fi?",
    "confirm_qr":       "Reset QR?",
    "confirm_both":     "Reset TUTTO?",
    "press_yes":        "Premi = SI",
    "rotate_cancel":    "Ruota = Annulla",
    "restarts_after":   "Riavvio dopo",

    "resetting":        "RIPRISTINO...",
    "action":           "Azione",
    "system_reboot":    "Riavvio del sistema",
    "please_wait":      "Attendere...",
    "files_deleted":    "FILE ELIMINATI",
    "rebooting":        "Riavvio...",
    "wait_reboot":      "Attendere riavvio",

    "setup_title":      "OTPi CONFIG",
    "setup_starting":   "Avvio config...",
    "setup_step1":      "PASSO 1",
    "setup_connect":    "Connetti al Wi-Fi:",
    "setup_step2":      "PASSO 2",
    "setup_browser":    "Apri il browser",
    "setup_navigate":   "Vai a:",
    "setup_step3":      "PASSO 3",
    "setup_form":       "Compila il modulo",
    "setup_on_web":     "sulla pagina web",
    "setup_complete":   "CONFIG COMPLETA",
    "setup_saved":      "Config salvata",
    "setup_restarting": "Riavvio...",
    "setup_error":      "ERRORE CONFIG",
    "setup_check":      "Controlla pagina web",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Ora sincronizzata",
    "starting":         "Avvio...",

    # Web portal strings
    "web_title": "OTPi Configurazione",
    "web_footer": "Indirizzo dispositivo",
    "web_nothing": "Niente da configurare.",
    "web_msg_both": "Fornire le credenziali Wi-Fi e un codice QR per continuare.",
    "web_msg_wifi": "Fornire le credenziali Wi-Fi per continuare.",
    "web_msg_qr": "Caricare il codice QR per continuare.",
    "web_wifi_title": "Configurazione Wi-Fi",
    "web_country_label": "Paese / Regione",
    "web_country_hint": "Imposta il dominio regolamentare Wi-Fi del tuo paese.",
    "web_lang_label": "Lingua display",
    "web_lang_hint": "Lingua per il display e questa pagina.",
    "web_ssid_label": "Rete (SSID)",
    "web_ssid_manual_label": "Inserire SSID manualmente",
    "web_ssid_placeholder": "Nome della tua rete",
    "web_password_label": "Password",
    "web_qr_title": "Codice QR OTP",
    "web_qr_label": "Carica immagine codice QR",
    "web_qr_hint": "Accetta PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Completa configurazione",
    "web_btn_wifi": "Salva Wi-Fi",
    "web_btn_qr": "Carica QR",
    "web_status_fill": "Compilare tutti i campi",
    "web_status_select": "Selezionare una rete e inserire la password",
    "web_status_ready": "Pronto per salvare",
    "web_status_ready_short": "Pronto per salvare",
    "web_status_saving": "Salvataggio...",
    "web_status_processing": "Elaborazione configurazione...",
    "web_missing_prefix": "Mancante",
    "web_scanning": "Scansione...",
    "web_no_networks": "Nessuna rete trovata",
    "web_select_network": "Seleziona la tua rete",
    "web_not_shown": "Il mio WiFi non appare...",
    "web_field_ssid": "SSID",
    "web_field_password": "Password",
    "web_field_qr": "Codice QR",
    "web_success_title": "Configurazione completata!",
    "web_success_saved": "Salvato con successo",
    "web_success_disconnect": "Puoi disconnetterti dalla rete di configurazione.",
    "web_success_restart": "Il dispositivo si riavvierà e inizierà a funzionare.",
    "web_success_totp": "I codici TOTP saranno mostrati sul display LED.",
    "web_error_incomplete": "Configurazione incompleta.",
    "web_error_back": "Indietro",
    "web_error_missing_wifi": "Credenziali Wi-Fi",
    "web_error_missing_qr": "Codice QR",
    "web_error_empty": "Il file caricato è vuoto",
    "web_error_not_image": "non è un file immagine valido",
},

# ─────────────────────────── Portuguese ──────────────────────────────
"pt": {
    "otp":              "OTP",
    "time":             "Tempo",
    "hue":              "Tom",
    "bright":           "Brilho",
    "press_next":       "[Pressione: Prox.]",

    "color_title":      "COR",
    "rotate_color":     "Girar: mudar Cor",
    "press_next_short": "[Pressione: Prox.]",

    "bright_title":     "BRILHO",
    "level":            "Nivel",
    "lang_title":       "IDIOMA",
    "rotate_lang":      "Girar: mudar idioma",

    "reset_title":      "MENU RESET",
    "next_screen":      "Proximo",
    "reset_wifi":       "Redefinir Wi-Fi",
    "reset_qr":         "Redefinir QR",
    "reset_both":       "Redefinir tudo",
    "scroll_hint":      "Girar para escolher, Pressionar para confirmar",

    "confirm_title":    "CONFIRMAR",
    "confirm_wifi":     "Redefinir Wi-Fi?",
    "confirm_qr":       "Redefinir QR?",
    "confirm_both":     "Redefinir TUDO?",
    "press_yes":        "Pressione = SIM",
    "rotate_cancel":    "Girar = Cancelar",
    "restarts_after":   "Reinicia depois",

    "resetting":        "REDEFININDO...",
    "action":           "Acao",
    "system_reboot":    "Reinicio do sistema",
    "please_wait":      "Aguarde...",
    "files_deleted":    "ARQUIVOS APAGADOS",
    "rebooting":        "Reiniciando...",
    "wait_reboot":      "Aguarde reinicio",

    "setup_title":      "OTPi CONFIG",
    "setup_starting":   "Iniciando config...",
    "setup_step1":      "PASSO 1",
    "setup_connect":    "Conectar ao Wi-Fi:",
    "setup_step2":      "PASSO 2",
    "setup_browser":    "Abrir navegador",
    "setup_navigate":   "Ir para:",
    "setup_step3":      "PASSO 3",
    "setup_form":       "Preencher formulario",
    "setup_on_web":     "na pagina web",
    "setup_complete":   "CONFIG COMPLETA",
    "setup_saved":      "Config salva",
    "setup_restarting": "Reiniciando...",
    "setup_error":      "ERRO DE CONFIG",
    "setup_check":      "Verificar pagina web",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Hora sincronizada",
    "starting":         "Iniciando...",

    # Web portal strings
    "web_title": "OTPi Configuração",
    "web_footer": "Endereço do dispositivo",
    "web_nothing": "Nada para configurar.",
    "web_msg_both": "Forneça as credenciais Wi-Fi e um código QR para continuar.",
    "web_msg_wifi": "Forneça as credenciais Wi-Fi para continuar.",
    "web_msg_qr": "Envie seu código QR para continuar.",
    "web_wifi_title": "Configuração Wi-Fi",
    "web_country_label": "País / Região",
    "web_country_hint": "Define o domínio regulatório Wi-Fi do seu país.",
    "web_lang_label": "Idioma da tela",
    "web_lang_hint": "Idioma para a tela e esta página.",
    "web_ssid_label": "Rede (SSID)",
    "web_ssid_manual_label": "Inserir SSID manualmente",
    "web_ssid_placeholder": "Nome da sua rede",
    "web_password_label": "Senha",
    "web_qr_title": "Código QR OTP",
    "web_qr_label": "Enviar imagem do código QR",
    "web_qr_hint": "Aceita PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Concluir configuração",
    "web_btn_wifi": "Salvar Wi-Fi",
    "web_btn_qr": "Enviar QR",
    "web_status_fill": "Preencha todos os campos",
    "web_status_select": "Selecione uma rede e insira a senha",
    "web_status_ready": "Pronto para salvar",
    "web_status_ready_short": "Pronto para salvar",
    "web_status_saving": "Salvando...",
    "web_status_processing": "Processando configuração...",
    "web_missing_prefix": "Faltando",
    "web_scanning": "Buscando...",
    "web_no_networks": "Nenhuma rede encontrada",
    "web_select_network": "Selecione sua rede",
    "web_not_shown": "Meu WiFi não aparece...",
    "web_field_ssid": "SSID",
    "web_field_password": "Senha",
    "web_field_qr": "Código QR",
    "web_success_title": "Configuração concluída!",
    "web_success_saved": "Salvo com sucesso",
    "web_success_disconnect": "Você pode desconectar da rede de configuração.",
    "web_success_restart": "O dispositivo vai reiniciar e começar a funcionar.",
    "web_success_totp": "Os códigos TOTP serão exibidos no display LED.",
    "web_error_incomplete": "Configuração incompleta.",
    "web_error_back": "Voltar",
    "web_error_missing_wifi": "Credenciais Wi-Fi",
    "web_error_missing_qr": "Código QR",
    "web_error_empty": "O arquivo enviado está vazio",
    "web_error_not_image": "não é um arquivo de imagem válido",
},

# ─────────────────────────── Dutch ───────────────────────────────────
"nl": {
    "otp":              "OTP",
    "time":             "Tijd",
    "hue":              "Tint",
    "bright":           "Helderh.",
    "press_next":       "[Druk: Volgende]",

    "color_title":      "KLEUR",
    "rotate_color":     "Draai: kleur wijzigen",
    "press_next_short": "[Druk: Volgende]",

    "bright_title":     "HELDERHEID",
    "level":            "Niveau",
    "lang_title":       "TAAL",
    "rotate_lang":      "Draai: taal wijzigen",

    "reset_title":      "RESET MENU",
    "next_screen":      "Volgende",
    "reset_wifi":       "Wi-Fi resetten",
    "reset_qr":         "QR resetten",
    "reset_both":       "Alles resetten",
    "scroll_hint":      "Draai om te kiezen, Druk om te bevestigen",

    "confirm_title":    "BEVESTIGEN",
    "confirm_wifi":     "Wi-Fi resetten?",
    "confirm_qr":       "QR resetten?",
    "confirm_both":     "ALLES resetten?",
    "press_yes":        "Druk = JA",
    "rotate_cancel":    "Draai = Annuleren",
    "restarts_after":   "Herstart hierna",

    "resetting":        "RESETTEN...",
    "action":           "Actie",
    "system_reboot":    "Systeem herstart",
    "please_wait":      "Even geduld...",
    "files_deleted":    "BESTANDEN GEWIST",
    "rebooting":        "Herstarten...",
    "wait_reboot":      "Wacht op herstart",

    "setup_title":      "OTPi INSTELLEN",
    "setup_starting":   "Instelling starten...",
    "setup_step1":      "STAP 1",
    "setup_connect":    "Verbind met Wi-Fi:",
    "setup_step2":      "STAP 2",
    "setup_browser":    "Open webbrowser",
    "setup_navigate":   "Ga naar:",
    "setup_step3":      "STAP 3",
    "setup_form":       "Vul formulier in",
    "setup_on_web":     "op de webpagina",
    "setup_complete":   "INSTELLING KLAAR",
    "setup_saved":      "Config opgeslagen",
    "setup_restarting": "Herstarten...",
    "setup_error":      "INSTELFOUT",
    "setup_check":      "Controleer webpagina",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Tijd gesynchroniseerd",
    "starting":         "Opstarten...",

    # Web portal strings
    "web_title": "OTPi Instellen",
    "web_footer": "Apparaatadres",
    "web_nothing": "Niets te configureren.",
    "web_msg_both": "Voer Wi-Fi gegevens en een QR-code in om door te gaan.",
    "web_msg_wifi": "Voer Wi-Fi gegevens in om door te gaan.",
    "web_msg_qr": "Upload uw QR-code om door te gaan.",
    "web_wifi_title": "Wi-Fi configuratie",
    "web_country_label": "Land / Regio",
    "web_country_hint": "Stelt het Wi-Fi-regelgevingsdomein in voor uw land.",
    "web_lang_label": "Weergavetaal",
    "web_lang_hint": "Taal voor het scherm en deze pagina.",
    "web_ssid_label": "Netwerk (SSID)",
    "web_ssid_manual_label": "SSID handmatig invoeren",
    "web_ssid_placeholder": "Uw netwerknaam",
    "web_password_label": "Wachtwoord",
    "web_qr_title": "OTP QR-code",
    "web_qr_label": "QR-code afbeelding uploaden",
    "web_qr_hint": "Accepteert PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Instelling voltooien",
    "web_btn_wifi": "Wi-Fi opslaan",
    "web_btn_qr": "QR uploaden",
    "web_status_fill": "Vul alle velden in",
    "web_status_select": "Selecteer een netwerk en voer wachtwoord in",
    "web_status_ready": "Klaar om op te slaan",
    "web_status_ready_short": "Klaar om op te slaan",
    "web_status_saving": "Opslaan...",
    "web_status_processing": "Configuratie verwerken...",
    "web_missing_prefix": "Ontbreekt",
    "web_scanning": "Zoeken...",
    "web_no_networks": "Geen netwerken gevonden",
    "web_select_network": "Selecteer uw netwerk",
    "web_not_shown": "Mijn WiFi staat er niet bij...",
    "web_field_ssid": "SSID",
    "web_field_password": "Wachtwoord",
    "web_field_qr": "QR-code",
    "web_success_title": "Instelling voltooid!",
    "web_success_saved": "Succesvol opgeslagen",
    "web_success_disconnect": "U kunt nu loskoppelen van het instellingsnetwerk.",
    "web_success_restart": "Het apparaat start opnieuw op.",
    "web_success_totp": "De TOTP-codes worden op het LED-display getoond.",
    "web_error_incomplete": "Instelling onvolledig.",
    "web_error_back": "Terug",
    "web_error_missing_wifi": "Wi-Fi gegevens",
    "web_error_missing_qr": "QR-code",
    "web_error_empty": "Geüpload bestand is leeg",
    "web_error_not_image": "is geen geldig afbeeldingsbestand",
},

# ─────────────────────────── Swedish ─────────────────────────────────
"sv": {
    "otp":              "OTP",
    "time":             "Tid",
    "hue":              "Nyans",
    "bright":           "Ljus",
    "press_next":       "[Tryck: Nasta]",

    "color_title":      "FARG",
    "rotate_color":     "Vrid: andra Farg",
    "press_next_short": "[Tryck: Nasta]",

    "bright_title":     "LJUSSTYRKA",
    "level":            "Niva",
    "lang_title":      "SPRAK",
    "rotate_lang":     "Drei: endre Sprak",
    "lang_title":      "SPRAK",
    "rotate_lang":     "Vrid: andra Sprak",

    "reset_title":      "ATERSTALL",
    "next_screen":      "Nasta",
    "reset_wifi":       "Aterstall Wi-Fi",
    "reset_qr":         "Aterstall QR",
    "reset_both":       "Aterstall allt",
    "scroll_hint":      "Vrid for att valja, Tryck for att bekrafta",

    "confirm_title":    "BEKRAFTA",
    "confirm_wifi":     "Aterstall Wi-Fi?",
    "confirm_qr":       "Aterstall QR?",
    "confirm_both":     "Aterstall ALLT?",
    "press_yes":        "Tryck = JA",
    "rotate_cancel":    "Vrid = Avbryt",
    "restarts_after":   "Omstart efter",

    "resetting":        "ATERSTALLER...",
    "action":           "Atgard",
    "system_reboot":    "Systemet startar om",
    "please_wait":      "Vanligen vanta...",
    "files_deleted":    "FILER RADERADE",
    "rebooting":        "Startar om...",
    "wait_reboot":      "Vanta pa omstart",

    "setup_title":      "OTPi INSTALLATION",
    "setup_starting":   "Startar install...",
    "setup_step1":      "STEG 1",
    "setup_connect":    "Anslut till Wi-Fi:",
    "setup_step2":      "STEG 2",
    "setup_browser":    "Oppna webblasare",
    "setup_navigate":   "Ga till:",
    "setup_step3":      "STEG 3",
    "setup_form":       "Fyll i formularet",
    "setup_on_web":     "pa webbsidan",
    "setup_complete":   "INSTALLATION KLAR",
    "setup_saved":      "Inst. sparade",
    "setup_restarting": "Startar om...",
    "setup_error":      "INSTALLATIONSFEL",
    "setup_check":      "Kontrollera sidan",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Tid synkroniserad",
    "starting":         "Startar...",

    # Web portal strings
    "web_title": "OTPi Installation",
    "web_footer": "Enhetsadress",
    "web_nothing": "Inget att konfigurera.",
    "web_msg_both": "Ange Wi-Fi-uppgifter och en QR-kod för att fortsätta.",
    "web_msg_wifi": "Ange Wi-Fi-uppgifter för att fortsätta.",
    "web_msg_qr": "Ladda upp din QR-kod för att fortsätta.",
    "web_wifi_title": "Wi-Fi konfiguration",
    "web_country_label": "Land / Region",
    "web_country_hint": "Ställer in Wi-Fi-reguleringsdomänen för ditt land.",
    "web_lang_label": "Visningsspråk",
    "web_lang_hint": "Språk för skärmen och denna sida.",
    "web_ssid_label": "Nätverk (SSID)",
    "web_ssid_manual_label": "Ange SSID manuellt",
    "web_ssid_placeholder": "Ditt nätverksnamn",
    "web_password_label": "Lösenord",
    "web_qr_title": "OTP QR-kod",
    "web_qr_label": "Ladda upp QR-kod bild",
    "web_qr_hint": "Accepterar PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Slutför installation",
    "web_btn_wifi": "Spara Wi-Fi",
    "web_btn_qr": "Ladda upp QR",
    "web_status_fill": "Fyll i alla fält",
    "web_status_select": "Välj ett nätverk och ange lösenord",
    "web_status_ready": "Redo att spara",
    "web_status_ready_short": "Redo att spara",
    "web_status_saving": "Sparar...",
    "web_status_processing": "Bearbetar konfiguration...",
    "web_missing_prefix": "Saknas",
    "web_scanning": "Söker...",
    "web_no_networks": "Inga nätverk hittades",
    "web_select_network": "Välj ditt nätverk",
    "web_not_shown": "Mitt WiFi visas inte...",
    "web_field_ssid": "SSID",
    "web_field_password": "Lösenord",
    "web_field_qr": "QR-kod",
    "web_success_title": "Installation klar!",
    "web_success_saved": "Sparades framgångsrikt",
    "web_success_disconnect": "Du kan nu koppla från installationsnätverket.",
    "web_success_restart": "Enheten startar om och börjar fungera.",
    "web_success_totp": "TOTP-koderna visas på LED-displayen.",
    "web_error_incomplete": "Installation ofullständig.",
    "web_error_back": "Tillbaka",
    "web_error_missing_wifi": "Wi-Fi-uppgifter",
    "web_error_missing_qr": "QR-kod",
    "web_error_empty": "Uppladdad fil är tom",
    "web_error_not_image": "är inte en giltig bildfil",
},

# ─────────────────────────── Danish ──────────────────────────────────
"da": {
    "otp":              "OTP",
    "time":             "Tid",
    "hue":              "Tone",
    "bright":           "Lys",
    "press_next":       "[Tryk: Naeste]",

    "color_title":      "FARVE",
    "rotate_color":     "Drej: skift Farve",
    "press_next_short": "[Tryk: Naeste]",

    "bright_title":     "LYSSTYRKE",
    "level":            "Niveau",
    "lang_title":       "SPROG",
    "rotate_lang":      "Drej: skift Sprog",

    "reset_title":      "NULSTIL MENU",
    "next_screen":      "Naeste",
    "reset_wifi":       "Nulstil Wi-Fi",
    "reset_qr":         "Nulstil QR",
    "reset_both":       "Nulstil alt",
    "scroll_hint":      "Drej for at vaelge, Tryk for at bekraefte",

    "confirm_title":    "BEKRAEFT",
    "confirm_wifi":     "Nulstil Wi-Fi?",
    "confirm_qr":       "Nulstil QR?",
    "confirm_both":     "Nulstil ALT?",
    "press_yes":        "Tryk = JA",
    "rotate_cancel":    "Drej = Annuller",
    "restarts_after":   "Genstart efter",

    "resetting":        "NULSTILLER...",
    "action":           "Handling",
    "system_reboot":    "System genstarter",
    "please_wait":      "Vent venligst...",
    "files_deleted":    "FILER SLETTET",
    "rebooting":        "Genstarter...",
    "wait_reboot":      "Vent pa genstart",

    "setup_title":      "OTPi OPSAETNING",
    "setup_starting":   "Starter opsaetning...",
    "setup_step1":      "TRIN 1",
    "setup_connect":    "Forbind til Wi-Fi:",
    "setup_step2":      "TRIN 2",
    "setup_browser":    "Abn webbrowser",
    "setup_navigate":   "Ga til:",
    "setup_step3":      "TRIN 3",
    "setup_form":       "Udfyld formularen",
    "setup_on_web":     "pa websiden",
    "setup_complete":   "OPSAETNING FAERDIG",
    "setup_saved":      "Config gemt",
    "setup_restarting": "Genstarter...",
    "setup_error":      "OPSAETNINGSFEJL",
    "setup_check":      "Tjek webside",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Tid synkroniseret",
    "starting":         "Starter...",

    # Web portal strings
    "web_title": "OTPi Oppsett",
    "web_footer": "Enhetsadresse",
    "web_nothing": "Ingenting å konfigurere.",
    "web_msg_both": "Oppgi Wi-Fi-opplysninger og en QR-kode for å fortsette.",
    "web_msg_wifi": "Oppgi Wi-Fi-opplysninger for å fortsette.",
    "web_msg_qr": "Last opp QR-koden din for å fortsette.",
    "web_wifi_title": "Wi-Fi konfigurasjon",
    "web_country_label": "Land / Region",
    "web_country_hint": "Angir Wi-Fi-reguleringsdomenet for ditt land.",
    "web_lang_label": "Visningsspråk",
    "web_lang_hint": "Språk for skjermen og denne siden.",
    "web_ssid_label": "Nettverk (SSID)",
    "web_ssid_manual_label": "Skriv inn SSID manuelt",
    "web_ssid_placeholder": "Ditt nettverksnavn",
    "web_password_label": "Passord",
    "web_qr_title": "OTP QR-kode",
    "web_qr_label": "Last opp QR-kode bilde",
    "web_qr_hint": "Godtar PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Fullfør oppsett",
    "web_btn_wifi": "Lagre Wi-Fi",
    "web_btn_qr": "Last opp QR",
    "web_status_fill": "Fyll ut alle felt",
    "web_status_select": "Velg et nettverk og skriv inn passord",
    "web_status_ready": "Klar til å lagre",
    "web_status_ready_short": "Klar til å lagre",
    "web_status_saving": "Lagrer...",
    "web_status_processing": "Behandler konfigurasjon...",
    "web_missing_prefix": "Mangler",
    "web_scanning": "Søker...",
    "web_no_networks": "Ingen nettverk funnet",
    "web_select_network": "Velg ditt nettverk",
    "web_not_shown": "Mitt WiFi vises ikke...",
    "web_field_ssid": "SSID",
    "web_field_password": "Passord",
    "web_field_qr": "QR-kode",
    "web_success_title": "Oppsett fullført!",
    "web_success_saved": "Lagret",
    "web_success_disconnect": "Du kan nå koble fra oppsettsnettverket.",
    "web_success_restart": "Enheten starter på nytt og begynner å fungere.",
    "web_success_totp": "TOTP-kodene vises på LED-displayet.",
    "web_error_incomplete": "Oppsett ufullstendig.",
    "web_error_back": "Tilbake",
    "web_error_missing_wifi": "Wi-Fi-opplysninger",
    "web_error_missing_qr": "QR-kode",
    "web_error_empty": "Opplastet fil er tom",
    "web_error_not_image": "er ikke en gyldig bildefil",

    # Web portal strings
    "web_title": "OTPi Opsætning",
    "web_footer": "Enhedsadresse",
    "web_nothing": "Intet at konfigurere.",
    "web_msg_both": "Angiv Wi-Fi oplysninger og en QR-kode for at fortsætte.",
    "web_msg_wifi": "Angiv Wi-Fi oplysninger for at fortsætte.",
    "web_msg_qr": "Upload din QR-kode for at fortsætte.",
    "web_wifi_title": "Wi-Fi konfiguration",
    "web_country_label": "Land / Region",
    "web_country_hint": "Indstiller Wi-Fi reguleringsdomænet for dit land.",
    "web_lang_label": "Visningssprog",
    "web_lang_hint": "Sprog for skærmen og denne side.",
    "web_ssid_label": "Netværk (SSID)",
    "web_ssid_manual_label": "Indtast SSID manuelt",
    "web_ssid_placeholder": "Dit netværksnavn",
    "web_password_label": "Adgangskode",
    "web_qr_title": "OTP QR-kode",
    "web_qr_label": "Upload QR-kode billede",
    "web_qr_hint": "Accepterer PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Fuldfør opsætning",
    "web_btn_wifi": "Gem Wi-Fi",
    "web_btn_qr": "Upload QR",
    "web_status_fill": "Udfyld alle felter",
    "web_status_select": "Vælg et netværk og indtast adgangskode",
    "web_status_ready": "Klar til at gemme",
    "web_status_ready_short": "Klar til at gemme",
    "web_status_saving": "Gemmer...",
    "web_status_processing": "Behandler konfiguration...",
    "web_missing_prefix": "Mangler",
    "web_scanning": "Søger...",
    "web_no_networks": "Ingen netværk fundet",
    "web_select_network": "Vælg dit netværk",
    "web_not_shown": "Mit WiFi vises ikke...",
    "web_field_ssid": "SSID",
    "web_field_password": "Adgangskode",
    "web_field_qr": "QR-kode",
    "web_success_title": "Opsætning færdig!",
    "web_success_saved": "Gemt med succes",
    "web_success_disconnect": "Du kan nu afbryde forbindelsen til opsætningsnetværket.",
    "web_success_restart": "Enheden genstarter og begynder at fungere.",
    "web_success_totp": "TOTP-koderne vises på LED-displayet.",
    "web_error_incomplete": "Opsætning ufuldstændig.",
    "web_error_back": "Tilbage",
    "web_error_missing_wifi": "Wi-Fi oplysninger",
    "web_error_missing_qr": "QR-kode",
    "web_error_empty": "Uploadet fil er tom",
    "web_error_not_image": "er ikke en gyldig billedfil",
},

# ─────────────────────────── Norwegian ───────────────────────────────
"no": {
    "otp":              "OTP",
    "time":             "Tid",
    "hue":              "Tone",
    "bright":           "Lys",
    "press_next":       "[Trykk: Neste]",

    "color_title":      "FARGE",
    "rotate_color":     "Drei: endre Farge",
    "press_next_short": "[Trykk: Neste]",

    "bright_title":     "LYSSTYRKE",
    "level":            "Niva",
    "lang_title":       "SPRAK",
    "rotate_lang":      "Drei: endre Sprak",

    "reset_title":      "TILBAKESTILL",
    "next_screen":      "Neste",
    "reset_wifi":       "Tilbakestill Wi-Fi",
    "reset_qr":         "Tilbakestill QR",
    "reset_both":       "Tilbakestill alt",
    "scroll_hint":      "Drei for a velge, Trykk for a bekrefte",

    "confirm_title":    "BEKREFT",
    "confirm_wifi":     "Tilbakest. Wi-Fi?",
    "confirm_qr":       "Tilbakest. QR?",
    "confirm_both":     "Tilbakest. ALT?",
    "press_yes":        "Trykk = JA",
    "rotate_cancel":    "Drei = Avbryt",
    "restarts_after":   "Omstart etter",

    "resetting":        "TILBAKESTILLER...",
    "action":           "Handling",
    "system_reboot":    "Systemet starter om",
    "please_wait":      "Vennligst vent...",
    "files_deleted":    "FILER SLETTET",
    "rebooting":        "Starter om...",
    "wait_reboot":      "Vent pa omstart",

    "setup_title":      "OTPi OPPSETT",
    "setup_starting":   "Starter oppsett...",
    "setup_step1":      "STEG 1",
    "setup_connect":    "Koble til Wi-Fi:",
    "setup_step2":      "STEG 2",
    "setup_browser":    "Apne nettleser",
    "setup_navigate":   "Ga til:",
    "setup_step3":      "STEG 3",
    "setup_form":       "Fyll ut skjemaet",
    "setup_on_web":     "pa nettsiden",
    "setup_complete":   "OPPSETT FERDIG",
    "setup_saved":      "Config lagret",
    "setup_restarting": "Starter om...",
    "setup_error":      "OPPSETTFEIL",
    "setup_check":      "Sjekk nettside",

    "wifi_ok":          "Wi-Fi OK",
    "time_ok":          "Tid synkronisert",
    "starting":         "Starter...",

    # Web portal strings
    "web_title": "OTPi Oppsett",
    "web_footer": "Enhetsadresse",
    "web_nothing": "Ingenting å konfigurere.",
    "web_msg_both": "Oppgi Wi-Fi-opplysninger og en QR-kode for å fortsette.",
    "web_msg_wifi": "Oppgi Wi-Fi-opplysninger for å fortsette.",
    "web_msg_qr": "Last opp QR-koden din for å fortsette.",
    "web_wifi_title": "Wi-Fi konfigurasjon",
    "web_country_label": "Land / Region",
    "web_country_hint": "Angir Wi-Fi-reguleringsdomenet for ditt land.",
    "web_lang_label": "Visningsspråk",
    "web_lang_hint": "Språk for skjermen og denne siden.",
    "web_ssid_label": "Nettverk (SSID)",
    "web_ssid_manual_label": "Skriv inn SSID manuelt",
    "web_ssid_placeholder": "Ditt nettverksnavn",
    "web_password_label": "Passord",
    "web_qr_title": "OTP QR-kode",
    "web_qr_label": "Last opp QR-kode bilde",
    "web_qr_hint": "Godtar PNG, JPEG, GIF, BMP, TIFF, WebP.",
    "web_btn_setup": "Fullfør oppsett",
    "web_btn_wifi": "Lagre Wi-Fi",
    "web_btn_qr": "Last opp QR",
    "web_status_fill": "Fyll ut alle felt",
    "web_status_select": "Velg et nettverk og skriv inn passord",
    "web_status_ready": "Klar til å lagre",
    "web_status_ready_short": "Klar til å lagre",
    "web_status_saving": "Lagrer...",
    "web_status_processing": "Behandler konfigurasjon...",
    "web_missing_prefix": "Mangler",
    "web_scanning": "Søker...",
    "web_no_networks": "Ingen nettverk funnet",
    "web_select_network": "Velg ditt nettverk",
    "web_not_shown": "Mitt WiFi vises ikke...",
    "web_field_ssid": "SSID",
    "web_field_password": "Passord",
    "web_field_qr": "QR-kode",
    "web_success_title": "Oppsett fullført!",
    "web_success_saved": "Lagret",
    "web_success_disconnect": "Du kan nå koble fra oppsettsnettverket.",
    "web_success_restart": "Enheten starter på nytt og begynner å fungere.",
    "web_success_totp": "TOTP-kodene vises på LED-displayet.",
    "web_error_incomplete": "Oppsett ufullstendig.",
    "web_error_back": "Tilbake",
    "web_error_missing_wifi": "Wi-Fi-opplysninger",
    "web_error_missing_qr": "QR-kode",
    "web_error_empty": "Opplastet fil er tom",
    "web_error_not_image": "er ikke en gyldig bildefil",
},

}  # end STRINGS
